# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ca288d2e20eebaffba5788e624d628f44c35b49d831a028e93ddf5a47c8c8f7b46d412f5f70b627630b49f969215a6674842f3c2b24e22cc3e5009858422ad

test:
  secret_key_base: 7aaffaad23636c04a3098deafd8647d842b4ca3475d61171fca1e0d6e100bdb800a8d5e2157842308be8b487f6b0afaef29d2248c50fb7dd968d038c8281d7eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
